# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy web app

on:
  push:
    branches: 
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # install dependencies, build, and test
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v1
        with:
          app-name: joeplumb
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}

